This project consists of all the basics of springboot that I have learnt from this tutorial:

https://www.youtube.com/watch?v=msXL2oDexqw&list=PLmbC-xnvykcghOSOJ1ZF6ja3aOgZAgaMO

For theory check videos: 1 to 9, 13-14, 15,

=== Endpoints that are built in this project:

1. GET /topics - get all the topics
2. GET /topics/id - get just one topic with the corresponding `id`
3. POST /topics  - add a new topic
4. PUT /topics/id  -  update a topic
5. DELETE /topics/id  - deletes the particular topic

=== Springboot annotations:

1. @SpringBootApplication
2. @RestController
 - @RequestMapping(value = "/path/{var}?param=123", method ="RequestMethod.GET")
 - @GetMapping(value = "/path")
 - @PathVariable("var")
 - @RequestBody - used for request bodies in PUT, POST
 - @RequestParam("param")
3. @Service
4. @Autowired

=== Configuring a springboot app.
Using  a `application.properties` file enables one to configure certain properties for the springboot app.
There are certain keys available which need to be defined in the app.props file as per the requirement.
These predefined keys can be found in : https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

=== Project setup in local:
1. mark `src` folder as source folder in the module settings in IntelliJ
2. you can changed the server.port in application.properties file as per your need